src/viz_app/urls.py
from django.urls import path

from . import views
from django.contrib.auth import views as auth_views

app_name = 'viz_app'
urlpatterns = [
    path('', views.home, name='home'),
    path('other_home/', views.home, name='home2'),
    path('about/', views.about, name='about'),
    path('other_about', views.about, name='about2'),
    path('chart/study-trends/', views.study_trends, name='study_trends'),
    path('chart/study-trends-2/', views.study_trends, name='study_trends2'),
    path('chart/depression-levels/', views.depression_levels, name='depression_levels'),
    path('chart/depression-levels-2/', views.depression_levels, name='depression_levels2'),
    path('chart/weekly-trends/', views.weekly_trends, name='weekly_trends'),
    path('chart/weekly-trends-2/', views.weekly_trends, name='weekly_trends2'),
    path('chart/daily-trends/', views.daily_trends, name='daily_trends'),
    path('chart/daily-trends-2/', views.daily_trends, name='daily_trends2'),
    path('chart/scatter-plot/', views.scatter_plot, name='scatter_plot'),
    path('chart/scatter-plot-2/', views.scatter_plot, name='scatter_plot2'),
    path('chart/sleep-data/', views.sleep_data, name='sleep_data'),
    path('chart/sleep-data-2/', views.sleep_data, name='sleep_data2'),
    path('chart/demographics/', views.demographics, name='demographics'),
    path('chart/demographics-2/', views.demographics, name='demographics2'),
    path('incomplete_login', views.incomplete, name='incomplete'),
    path('index/', views.index, name='index'),
    path('other_index/', views.index, name='index2'),
    path('publications/', views.publications, name='publications'),
    path('other_publications/', views.publications, name='publications2'),
    path('team/', views.team, name='team'),
    path('other_team/', views.team, name='team2'),
    path('faq/', views.faq, name='faq'),
    path('other_faq/', views.faq, name='faq2'),
    path('for-participants/', views.for_participants, name='for_participants'),
    path('for-participants-2/', views.for_participants, name='for_participants2'),
    path('for-admin/', views.for_admin, name='for_admin'),
    path('for-admin-2/', views.for_admin, name='for_admin2'),
    path('get-study-trends-data/', views.get_study_trends_data, name='get_study_trends_data'),
    path('get-depression-scale-data/', views.get_depression_scale_data, name='get_depression_scale_data'),
    path('get-weekly-trends-data/', views.get_weekly_trends_data, name='get_weekly_trends_data'),
    path('get-daily-trends-data/', views.get_daily_trends_data, name='get_daily_trends_data'),
    path('get-scatter-plot-data/', views.get_scatter_plot_data, name='get_scatter_plot_data'),
    path('get-sleep-data/', views.get_sleep_data, name='get_sleep_data'),
    path('get-demographics-data/', views.get_demographics_data, name='get_demographics_data'),
    path('get-user-type/', views.get_viewing_permission, name='get_viewing_permission'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout')
]

src/viz_platform/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('viz_app.urls')),
]

urlpatterns += staticfiles_urlpatterns()

src/viz_app/models.py
from django.db import models

# Create your models here.


class PhysData(models.Model):
    name = models.CharField(null=True, max_length=4)
    date = models.DateTimeField(null=True)
    category = models.CharField(null=True, max_length=200)
    hand = models.CharField(null=True, max_length=5)
    interval = models.CharField(null=True, max_length=10)
    measurement = models.FloatField(null=True)
    fraction = models.FloatField(null=True)
    group = models.CharField(null=True, max_length=200)

    def __str__(self):
        return "Date: " + str(self.date) + " Measurement: " + str(self.measurement)

    def __hash__(self):
        return hash((self.name, self.date, self.category, self.interval, self.measurement))

class DepData(models.Model):
    name = models.CharField(null=True, max_length=4)
    date = models.DateTimeField(null=True)
    category = models.CharField(null=True, max_length=200)
    interval = models.CharField(null=True, max_length=10)
    measurement = models.FloatField(null=True)
    group = models.CharField(null=True, max_length=200)

    def __str__(self):
        return "Date: " + str(self.date) + " Measurement: " + str(self.measurement)

    def __hash__(self):
        return hash((self.name, self.date, self.category, self.interval, self.measurement))


class PhoneData(models.Model):
    name = models.CharField(null=True, max_length=4)
    date = models.DateTimeField(null=True)
    category = models.CharField(null=True, max_length=200)
    interval = models.CharField(null=True, max_length=10)
    measurement = models.FloatField(null=True)
    group = models.CharField(null=True, max_length=200)

    def __str__(self):
        return "Date: " + str(self.date) + " Measurement: " + str(self.measurement)

    def __hash__(self):
        return hash((self.name, self.date, self.category, self.interval, self.measurement))


class WeatherData(models.Model):
    name = models.CharField(null=True, max_length=4)
    date = models.DateTimeField(null=True)
    category = models.CharField(null=True, max_length=200)
    measurement = models.FloatField(null=True)
    group = models.CharField(null=True, max_length=200)
    interval = models.CharField(default='24hrs', max_length=10)

    def __str__(self):
        return "Date: " + str(self.date) + " Measurement: " + str(self.measurement)

    def __hash__(self):
        return hash((self.name, self.date, self.category, self.measurement))


class SleepData(models.Model):
    name = models.CharField(max_length=4)
    date = models.DateTimeField()
    category = models.CharField(max_length=20)
    is_asleep = models.NullBooleanField()
    interval = models.CharField(default='10mins', max_length=10)
    regularity = models.FloatField(null=True)

    def __str__(self):
        return "Participant: " + str(self.name) + "Date: " + str(self.date) + " Is asleep: " + str(self.is_asleep)

    def __hash__(self):
        return hash((self.name, self.date, self.category, self.is_asleep))


class DemographicData(models.Model):
    ethnicity_choices = [('hispanic', 'Hispanic or Latino'),
                         ('non-hispanic', 'Non-Hispanic or Latino')]
    study_group_choices = [('MDD', 'Major Depressive Disorder'),
                           ('HC', 'Healthy Control')]
    sex_choices = [('male', 'Male'),
                   ('female', 'Female')]

    name = models.CharField(max_length=4, null=False)
    age = models.FloatField(null=False)
    in_psychotherapy = models.NullBooleanField()
    number_trials = models.FloatField(null=False)
    ethnicity = models.CharField(max_length=50, null=False, choices=ethnicity_choices)
    is_white = models.BooleanField(null=False)
    is_black_african_american = models.BooleanField(null=False)
    is_asian = models.BooleanField(null=False)
    is_hawaiian_pacific_islander = models.BooleanField(null=False)
    is_american_indian_alaska_native = models.BooleanField(null=False)
    is_other_race = models.BooleanField(null=False)
    treatment_length = models.FloatField(null=False)
    study_group = models.CharField(null=False, max_length=7, choices=study_group_choices)
    sex = models.CharField(null=False, max_length=7, choices=sex_choices)


class SitePrivileges(models.Model):

    class Meta:

        managed = False

        permissions = (
            ("aggregate", "Can view aggregate data"),
            ("individual", "Can view specific individual data"),
            ("study1", "Can view GCS study data"),
            ("study2", "Can view followup study data")
        )

src/viz_app/views.py
import json
import math

from django import forms
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib.auth.decorators import login_required, permission_required
from django.db.models.functions import ExtractMinute, ExtractHour, ExtractWeekDay, TruncDay
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .value_mappings import *


# Create your views here.
STUDY2_KEY = "2"

def get_dict(request, visualization=False):
    name = request.resolver_match.view_name
    if visualization:
        parent = 'viz_app/visualization_base2.html' if STUDY2_KEY in name else 'viz_app/visualization_base.html'
    else:
        parent = 'viz_app/base2.html' if STUDY2_KEY in name else 'viz_app/base.html'
    value = "2" if STUDY2_KEY in name else "1"
    return {"parent":parent, "value":value}

@login_required
def index(request):
    return render(request, 'viz_app/index.html', get_dict(request))

@login_required
def study_trends(request):
    name = request.resolver_match.view_name
    patients = PARTICIPANTS
    if STUDY2_KEY in name:
        patients = PARTICIPANTS2
    context = {"names": patients, "category_mapping": sorted(CATEGORY_MAPPING_DAILY.items()), "new_category_mapping": sorted(NEW_CATEGORY_MAPPING_DAILY.items()), "categories": sorted(CATEGORIES_DAILY.items()), "new_categories": sorted(NEW_CATEGORIES.items())}
    context.update(get_dict(request, True))
    return render(request, 'viz_app/study_trends.html', context)

@login_required
def depression_levels(request):
    name = request.resolver_match.view_name
    patients = PARTICIPANTS
    if STUDY2_KEY in name:
        patients = PARTICIPANTS2
    context = {"names": patients, "category_mapping": sorted(DEPRESSION_CATEGORY_MAPPING.items()), "new_category_mapping": sorted(DEPRESSION_CATEGORY_MAPPING.items()), "categories": sorted(DEPRESSION_CATEGORIES.items()), "new_categories": sorted(DEPRESSION_CATEGORIES.items())}
    context.update(get_dict(request, True))
    return render(request, 'viz_app/depression_levels.html', context)

@permission_required("viz_app.aggregate")
@login_required
def weekly_trends(request):
    context = {"category_mapping": sorted(CATEGORY_MAPPING_DAILY.items()), "categories":sorted(CATEGORIES_DAILY.items())}
    context.update(get_dict(request, True))
    return render(request, 'viz_app/weekly_trends.html', context)

@login_required
def daily_trends(request):
    name = request.resolver_match.view_name
    patients = PARTICIPANTS
    if STUDY2_KEY in name:
        patients = PARTICIPANTS2
    context = {"names": patients, "category_mapping": sorted(CATEGORY_MAPPING_HOURLY.items()), "new_category_mapping": sorted(NEW_CATEGORY_MAPPING_DAILY.items()), "categories": sorted(CATEGORIES_HOURLY.items()), "new_categories": sorted(NEW_CATEGORIES.items())}
    context.update(get_dict(request, True))
    return render(request, 'viz_app/daily_trends.html', context)

@login_required
def scatter_plot(request):
    context = {"category_mapping": sorted(CATEGORY_MAPPING_DAILY.items()), "new_category_mapping": sorted(NEW_CATEGORY_MAPPING_DAILY.items()), "categories": sorted(CATEGORIES_DAILY.items()), "new_categories": sorted(NEW_CATEGORIES.items())}
    context.update(get_dict(request, True))
    return render(request, 'viz_app/scatter_plot.html', context)

@login_required
def sleep_data(request):
    name = request.resolver_match.view_name
    patients = PARTICIPANTS
    if STUDY2_KEY in name:
        patients = PARTICIPANTS2
    context = {"names": patients}
    context.update(get_dict(request, True))
    return render(request, 'viz_app/sleep_data.html', context)


@permission_required("viz_app.aggregate")
@login_required
def demographics(request):

    return render(request, 'viz_app/demographics.html', get_dict(request, True))

def home(request):
    return render(request, 'viz_app/home.html', get_dict(request))

def incomplete(request):
    return render(request, 'viz_app/incomplete.html')

def about(request):
    return render(request, 'viz_app/about.html', get_dict(request))

def publications(request):
    return render(request, 'viz_app/publications.html', get_dict(request))

def team(request):
    return render(request, 'viz_app/team.html', get_dict(request))

def for_admin(request):
    return render(request, 'viz_app/for_admin.html', get_dict(request))

def for_participants(request):
    return render(request, 'viz_app/for_participants.html', get_dict(request))


def faq(request):
    return render(request, 'viz_app/faq.html', get_dict(request))

class LoginForm(forms.Form):
    username = forms.CharField(label='Username', widget=forms.TextInput(attrs={'class': 'form-input', 'id': 'id_username'}))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-input', 'id': 'id_password'}))


def login(request):
    if request.user.is_authenticated:
        print("User is authenticated")
        if request.user.has_perm('viz_app.study1') or request.user.has_perm('viz_app.aggregate'):
            return HttpResponseRedirect(reverse('viz_app:home'))
        elif request.user.has_perm('viz_app.study2'):
            return HttpResponseRedirect(reverse('viz_app:home2'))
        else:
            return HttpResponseRedirect(reverse('viz_app:incomplete'))
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                auth_login(request, user)
                if user.has_perm('viz_app.study1') or request.user.has_perm('viz_app.aggregate'):
                    return HttpResponseRedirect(reverse('viz_app:home'))
                elif user.has_perm('viz_app.study2'):
                    return HttpResponseRedirect(reverse('viz_app:home2'))
                else:
                    return HttpResponseRedirect(reverse('viz_app:incomplete'))
            else:
                form.add_error('username', 'invalid auth')
    else:
        form = LoginForm()
    context = {'form': form, 'was_redirected': request.GET.get('next') != None}
    return render(request, 'registration/login.html', context)


def logout(request):
    auth_logout(request)
    return HttpResponseRedirect(reverse('viz_app:home'))


@login_required
def get_study_trends_data(request):
    try:
        type = request.GET.get("type")
        group = request.GET.get("group")
        number = request.GET.get("number")
        model = None
        for m in DATABASE_MAPPING:
            if type in DATABASE_MAPPING[m]:
                model = m
        assert model is not None
        if group == "None":
            name = request.GET.get("name")
            if type in SEPARATE_HANDS:
                subject_data = {"left": {"dates": [], "measurements": []},
                                "right": {"dates": [], "measurements": []},
                                }
                raw_data = list(model.objects
                                .filter(name=name,
                                        category=type,
                                        interval="24hrs")
                                .order_by("date")
                                .values("date", "measurement", "hand"))
                for x in raw_data:
                    subject_data[x["hand"]]["dates"].append(x["date"].isoformat())
                    subject_data[x["hand"]]["measurements"].append(x["measurement"])
                return HttpResponse(json.dumps({"subject_data": subject_data}))
            else:
                val = 60 if type in PHONES else 1
                subject_data = {None: {"dates": [], "measurements": []},
                                }
                print(type)
                if (type == "Time in Activity Levels"):
                    print("whaaaaaaat")
                    sedentary = list(model.objects
                                    .filter(name=name,
                                            category="Sedentary Activity",
                                            interval="24hrs")
                                    .order_by("date")
                                    .values("date", "measurement"))
                    light = list(model.objects
                                    .filter(name=name,
                                            category="Light Activity",
                                            interval="24hrs")
                                    .order_by("date")
                                    .values("date", "measurement"))
                    moderate = list(model.objects
                                    .filter(name=name,
                                            category="Moderate Activity",
                                            interval="24hrs")
                                    .order_by("date")
                                    .values("date", "measurement"))
                    vigorous = list(model.objects
                                    .filter(name=name,
                                            category="Vigorous Activity",
                                            interval="24hrs")
                                    .order_by("date")
                                    .values("date", "measurement"))

                    for time in range(len(sedentary)):
                        print(sedentary[time]["date"])
                        subject_data[None]["dates"].append(sedentary[time]["date"].isoformat())
                        subject_data[None]["measurements"].append([sedentary[time]["measurement"], light[time]["measurement"], moderate[time]["measurement"], vigorous[time]["measurement"]])

                    print(subject_data)
                elif type == "Activity Level":

src/viz_app/templates/viz_app/daily_trends.html
{% extends parent %}

{% load staticfiles %}
{% load static from staticfiles %}
{% block title %}GCS - Daily Trends{% endblock %}
{% block header %}
    <h1>Daily Trends</h1>
{% endblock %}

{% block description%}
    <b>
        A time series showing the trend of a measured or reported variable over the course of the 24 hours in a day.
        If no data was collected in any particular hour for a participant, no data point is
        generated for that hour.
    </b>
    <br>
    Select options from the drop-down menus to see different data. Hover, click, and scroll on the graph/legend to
    see the data in more detail.
{% endblock %}

{% block options %}
<div class="dropdown-container">
        <h3>Select a data category:</h3>
        <div class="search-categories">
            <div class="select">
                <select id="category_dropdown">
                    {% if perms.viz_app.individual and not perms.viz_app.aggregate %}
                        {%  for category_value, category_label in new_categories %}
                            <option value="{{ category_value }}">{{ category_label }}</option>
                        {% endfor %}
                    {% else %}
                        {%  for category_value, category_label in categories %}
                            <option value="{{ category_value }}">{{ category_label }}</option>
                        {% endfor %}
                    {% endif %}
                </select>
            </div>
        </div>
    </div>
    {% if perms.viz_app.individual and not perms.viz_app.aggregate %}
        {% for category, types in new_category_mapping %}
            <div class="dropdown-container data-dropdown-container" id="{{ category }}_dropdown_container">
                <h3>Select a data type:</h3>
                <div class="search-categories">
                    <div class="select">
                        <select class="type_dropdown" id="{{ category }}_dropdown">
                            {% for type in types %}
                                <option value="{{ type }}">{{ type }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
        {% for category, types in category_mapping %}
        <div class="dropdown-container data-dropdown-container" id="{{ category }}_dropdown_container">
            <h3>Select a data type:</h3>
            <div class="search-categories">
                <div class="select">
                    <select class="type_dropdown" id="{{ category }}_dropdown">
                        {% for type in types %}
                            <option value="{{ type }}">{{ type }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
        </div>
        {% endfor %}
    {% endif %}
    <div class="dropdown-container"
         {% if perms.viz_app.individual and not perms.viz_app.aggregate %}style="display: none;"{% endif %}>
        <h3>Select a group (or none):</h3>
        <div class="search-categories">
            <div class="select">
                <select class="chart-dropdown" id="group_dropdown">
                    {% if perms.viz_app.aggregate %}
                    <option value="All" selected>All</option>
                    <option value="Depression">Depression Status</option>
                    <option value="Gender">Gender</option>
                    <option value="Marital">Marital Status</option>
                    <option value="Employment">Employment Status</option>
                    <option value="Age">Age</option>
                    <option value="Psychotherapy">Psychotherapy</option>
                    <option value="Episode Length">Episode Length</option>
                    <option value="Episode Type">Episode Type</option>
                    <option value="Phobia">Social Phobia</option>
                    <option value="Anxiety">Generalized Anxiety Disorder</option>
                    <option value="Current Medication">Current Medication Status</option>
                    {% endif %}
                    {% if perms.viz_app.individual %}
                    <option value="None">None (Individual)</option>
                    {% endif %}
                </select>
            </div>
        </div>
    </div>
    {% if perms.viz_app.aggregate %}
    <div class="dropdown-container" id="aggregation_container">
        <h3>Select an aggregation method:</h3>
        <div class="search-categories">
            <div class="select">
                <select id="aggregation_dropdown">
                    <option value="Mean" selected>Mean</option>
                    <option value="Median">Median</option>
                    <option value="Max">Max</option>
                    <option value="Min">Min</option>
                    <option value="Std Dev">Standard Deviation</option>
                </select>
            </div>
        </div>
    </div>
    {% endif %}
    <div class="dropdown-container" id="names_container" style="display: none;">
        <h3>Select an individual:</h3>
        <div class="search-categories">
            <div class="select">
                <select id="names_dropdown">
                    {% if perms.viz_app.individual and not perms.viz_app.aggregate %}
                        <option value="{{ user.username }}">{{ user.username }}</option>
                    {% else %}
                        {% for name in names %}
                            <option value="{{ name }}">{{ name }}</option>
                        {% endfor %}
                    {% endif %}
                </select>
            </div>
        </div>
    </div>
{% endblock %}

{% block selection_descriptions %}
    <div class="description-label category-description">Data Category</div>
    <div class="description-label type-description">Data Type</div>
    <div class="description-label preprocess-description">Preprocessing</div>
    <div class="description-label group-description"
         {% if perms.viz_app.individual and not perms.viz_app.aggregate %}style="display: none;"{% endif %}>Group</div>
    <div class="description-label aggregation-description"
         {% if perms.viz_app.individual and not perms.viz_app.aggregate %}style="display: none;"{% endif %}>Aggregation</div>
    <div class="description-label individual-description" style="display: none;">Individual</div>
{% endblock %}

{% block script %}
    {{ block.super }}
    <script src="{% static 'js/daily_trends.js' %}"></script>
    <script>
        $('.navbar-nav .nav-item.active').removeClass('active');
        $('#data-visualization').addClass('active');
    </script>
{% endblock %}

src/viz_app/templates/viz_app/home.html
{% extends parent %} {% load staticfiles %} {% load static from staticfiles %}
{% block title %}GCS - Home{% endblock %}
{% block content %}
<div class="content">
  <div class="home-section">
    <h1>
      <strong
        >Welcome to The Sensor-Based Characterization of Depression Study!<br />(SENSCODE)</strong
      >
    </h1>
  </div>
  <div class="img-container-home">
    <img class='mgh-logo' src="{% static "img/mghlogo.png" %}" alt="The Empatica
    E4 Wristband">
    <div class="mgh-words-container">
      <img src="{% static "img/mgh-logo.png" %}" alt="The Empatica E4
      Wristband">
    </div>
    <div class="affective-computing-container">
      <img src="{% static "img/affective_computing.png" %}" alt="The Empatica E4
      Wristband">
    </div>
    <img class='media-lab-img' src="{% static "img/mitmedialab.png" %}" alt="The
    Empatica E4 Wristband">
  </div>
  <div id="home-page-more-info">
    <div class="home-study-section">
      <h2 class="study-name">
        More on the MGH-Psychiatry and MIT Media Lab Research Collaboration
      </h2>
      <div class="basic-information">
        <p style="margin: 0.4em 0.4em 2em 0.4em;">
          In 2015, the
          <a href="http://www.depressionmgh.org/about-us"
            >Depression Clinical and Research Program</a
          >
          at Massachusetts General Hospital (MGH) and the Massachusetts
          Institute of Technology Media Lab’s
          <a href="https://affect.media.mit.edu/index.php"
            >Affective Computing Group</a
          >
          joined forces to establish the MGH-MIT Alliance. The goal of this
          collaboration is to employ machine learning and artificial
          intelligence to digitally phenotype depression, which refers to
          exploring people’s interactions with various devices, including
          smartphones, to assess their well-being. This has led to the birth of
          two studies: the Grand Challenge Study and Sensor-Based
          Characterization of Depression (SENSCODE).
        </p>
        {% if request.user.is_authenticated %} {% if perms.viz_app.study_1 %}
        <a id="learn-more" href="{% url 'viz_app:about' %}">Learn More!</a>
        {% else %}
        <a id="learn-more" href="{% url 'viz_app:about2' %}">Learn More!</a>
        {% endif %} {% else %}
        <a id="learn-more" href="{% url 'viz_app:about' %}">Learn More!</a>
        {% endif %}
      </div>
    </div>
    <div class="slideshow-container">
      <ul class="cb-slideshow">
        <li>
          <span>Image 01</span>
        </li>
        <li>
          <span>Image 02</span>
        </li>
        <li>
          <span>Image 03</span>
        </li>
        <li>
          <span>Image 04</span>
        </li>
        <li>
          <span>Image 05</span>
        </li>
        <li>
          <span>Image 06</span>
        </li>
      </ul>
    </div>
  </div>
  <div class="spacer"></div>
</div>
{% endblock %} {% block script %} {{ block.super }}
<script src="{% static 'js/photo_gallery.js' %}"></script>
<script>
    $('.navbar-nav .nav-item.active').removeClass('active');
    $('#home').addClass('active');
</script>
{% endblock %}

src/viz_app/templates/viz_app/index.html
{% extends parent %}

{% load staticfiles %}
{% load static from staticfiles %}
{% block title %}GCS - Index{% endblock %}
{% block content %}
<div class="content">
    <h1>Select a plot:</h1>

    <div class="graph_buttons">
        <div class="button_container">
            <a href="{% url 'viz_app:study_trends' %}">
                <img class="button" src="{% static 'img/study_trends.png' %}">
                <div class="middle">
                    <div class="text">Study Trends</div>
                </div>
            </a>
        </div>
        {% if perms.viz_app.aggregate %}
            <div class="button_container">
                <a href="{% url 'viz_app:weekly_trends' %}">
                    <img class="button" src="{% static 'img/weekly_trends.png' %}">
                    <div class="middle">
                        <div class="text">Weekly Trends</div>
                    </div>
                </a>
            </div>
        {% endif %}
        <div class="button_container">
            <a href="{% url 'viz_app:daily_trends' %}">
                <img class="button" src="{% static 'img/daily_trends.png' %}">
                <div class="middle">
                    <div class="text">Daily Trends</div>
                </div>
            </a>
        </div>
        <div class="button_container">
            <a href="{% url 'viz_app:scatter_plot' %}">
                <img class="button" src="{% static 'img/scatter_plot.png' %}">
                <div class="middle">
                    <div class="text">Scatter Plot</div>
                </div>
            </a>
        </div>
        <div class="button_container">
            <a href="{% url 'viz_app:sleep_data' %}">
                <img class="button" src="{% static 'img/sleep_data.png' %}">
                <div class="middle">
                    <div class="text">Sleep Data</div>
                </div>
            </a>
        </div>
        {% if perms.viz_app.aggregate %}
            <div class="button_container">
                <a href="{% url 'viz_app:demographics' %}">
                    <img class="button" src="{% static 'img/demographics.png' %}">
                    <div class="middle">
                        <div class="text">Demographics</div>
                    </div>
                </a>
            </div>
        {% endif %}
    </div>
</div>
{% endblock %} {% block script %} {{ block.super }}
<script>
    $('.navbar-nav .nav-item.active').removeClass('active');
    $('#data-visualization').addClass('active');
</script>
{% endblock %}